all:
  hosts:
    vps1:
      ansible_host: "{{ lookup('env', 'VPS_IP') }}"
      ansible_user: "{{ lookup('env', 'VPS_USER') | default('debian', true) }}"
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ConnectTimeout=15"
      ansible_become_password: "{{ lookup('env', 'VPS_PASSWORD') | default('', true) }}"
    vps2:
      ansible_host: "{{ lookup('env', 'VPS2_IP') }}"
      ansible_user: "{{ lookup('env', 'VPS2_USER') | default('debian', true) }}"
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ConnectTimeout=15"
      ansible_become_password: "{{ lookup('env', 'VPS2_PASSWORD') | default('', true) }}"
    backup:
      ansible_host: "{{ lookup('env', 'BACKUP_MACHINE_HOST') }}"
      ansible_user: "{{ lookup('env', 'BACKUP_MACHINE_USER') | default('c03rad0r', true) }}"
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ConnectTimeout=15"
  children:
    vps:
      hosts:
        vps1:
        vps2:
    m1:
      hosts:
        vps1:
    m2:
      hosts:
        vps2:
    backup_group:
      hosts:
        backup:
